### PR TITLE
fixes #26 - resources.find now checks if the sortBy is a typeof VIRTUAL 

### LINKED ISSUE #26: SequelizeDatabaseError: column Provider.name does not exist
**Describe the bug**
Cannot sort of virtual columns. This is either a bug in sequlize or unsupported use case. I will be updating a similar issue is sequalize that appears to be related. https://github.com/sequelize/sequelize/issues/10983

**Installed libraries and their versions**
```
"dependencies": {
    "admin-bro": "^2.2.12",
    "admin-bro-expressjs": "^2.0.5",
    "admin-bro-sequelizejs": "^0.4.1",
    "aws-sdk": "^2.666.0",
    "cron": "^1.7.2",
    "cron-parser": "^2.13.0",
    "dotenv": "^8.2.0",
    "express": "^4.17.1",
    "express-fileupload": "^1.1.7-alpha.3",
    "express-formidable": "^1.2.0",
    "fs-extra": "^8.1.0",
    "json2csv": "^4.5.4",
    "mirth-api": "^0.0.5",
    "moment": "^2.24.0",
    "morgan": "^1.10.0",
    "node-fetch": "^2.6.0",
    "nodemailer": "^6.3.1",
    "pg": "^7.14.0",
    "sequelize": "^5.21.2",
    "swagger-jsdoc": "^4.0.0",
    "vm2": "^3.8.4"
  }
```

**To Reproduce**
1. Create a model with a virtual field, example
```
/* jshint indent: 1 */

module.exports = (sequelize, DataTypes) => {
    let Provider = sequelize.define('Provider',
        {
            nationalProviderIdentifier: {
                type: DataTypes.INTEGER,
                allowNull: false,
                unique: true
            },
            familyName: {
                type: DataTypes.STRING,
                allowNull: false
            },
            givenName: {
                type: DataTypes.STRING,
                allowNull: false
            },
            additionalName: {
                type: DataTypes.STRING,
                allowNull: false,
                defaultValue: ''
            },
            name: {
                // type: DataTypes.VIRTUAL(DataTypes.STRING, ['givenName', 'familyName', 'additionalName']),
                type: DataTypes.VIRTUAL,
                get: function() {
                    return `${this.getDataValue('givenName')} ${this.getDataValue('familyName')} ${this.getDataValue('additionalName')}`.trim()
                }
            },
        }
    )

    return Provider
}
```
2. Open Admin Bro to the resource

**Expected behavior**
Throw an error to the effect of `Cannot sort on VIRTUAL Datatype "${sortBy}"! You can provide a different sort by field to avoid this issue, see: https://adminbro.com/ResourceOptions.html#sort`

Could sort by the primary key when the default sort by key is virtual but that could create an issue where it's not sorting as expect and the user has no clue why.

**Additional context**
Fix: https://github.com/SoftwareBrothers/admin-bro-sequelizejs/blob/master/src/resource.js
```
...
const { Op, DataTypes } = require('sequelize')
...
    const { direction, sortBy } = sort
    if (this.SequelizeModel.fieldRawAttributesMap[sortBy].type instanceof DataTypes.VIRTUAL) {
        throw new Error(`Cannot sort on VIRTUAL Datatype "${sortBy}" on resource "${this.SequelizeModel.name}"! You can provide a different sort by field to avoid this issue, see: https://adminbro.com/ResourceOptions.html#sort`)
    }
    const sequelizeObjects = await this.SequelizeModel
      .findAll({
        where: convertFilter(filter),
        limit,
        offset,
        order: [[sortBy, (direction || 'asc').toUpperCase()]],
      })
```

### PR DESCRIPTION
**Pull request by MichaelLeeHobbs**
fixes #26 - resources.find now checks if the sortBy is a typeof Sequlize.VIRTUAL and throws an error that it cannot sort by a typeof VIRTUAL and how to fix the issue

### CODE REVIEW

**Comment by MichaelLeeHobbs** [comment]
We should add regression tests but that is not something I have time for now. At the earliest, it would be a week or more before I have time for that.

**Comment by MichaelLeeHobbs** [comment]
Test added. Also committed changed to make dev work on Windows. I would have done this as a separate pull request but GitHub automatically added the commit to this pull request.

**Comment by wojtek-krysiak** [comment]
Hi @MichaelLeeHobbs - thanks for the PR. I was looking and it and I think that the simplest solution would be to disable the sorting for virtual properties instead of throwing errors. (in property override `isSortable` that it returns false for virtual properties).

Otherwise, it is a risk that this error will be thrown on production because the developer who implemented admin-bro simply didn't know about this and tester didn't click "sort" button.

What do you think?

**Comment by MichaelLeeHobbs** [comment]
I agree. I just hadn't got back around to updating this. Been a very busy couple of weeks. There are some other items I'd like to address in admin-bro-sequelizejs but for not I think the making the virtuals not sortable is the best solution.

**Comment by MichaelLeeHobbs** [comment]
I will do a clean fork and put the other changes into a new pull request.

**Comment by wojtek-krysiak** [comment]
hehe - the same here - busy 2 weeks. So I am closing this one for now.

**Pull request closed without merging**
