### PR TITLE
Fix string filter problem with multiple fields

### PR DESCRIPTION
**Pull request by ElvisYang**
Fix the problem for: When applying more than one string field for filtering, only the first field works, the others just override by the first one.

### CODE REVIEW

**Comment by ElvisYang** [comment]
@wojtek-krysiak could you review this PR?

**Comment by dziraf** [comment]
Looks good, can you fix the test (the missing comma) and I will merge the PR?

**Comment by ElvisYang** [comment]
@dziraf Thanks, I have fixed the test. so one more question, when this is merged in, when we can get this publish?

**Comment by Bkahler** [comment]
I am facing the same issue, would love to see this merged and available to use soon

**Comment by dziraf** [comment]
Could you also rebase your branch to this repo's master? I've pushed some changes to the same file recently and it looks odd to me that it doesn't show any conflicts...

Once all is good, I'll merge and this will be deployed soon after.

**Comment by ElvisYang** [comment]
@dziraf Done, hope this looks good now

**Comment by ElvisYang** [comment]
and do i need to change version number for publishing? https://github.com/SoftwareBrothers/admin-bro-sequelizejs/blob/master/package.json#L3

**Comment by dziraf** [comment]
Thanks! Merging it now.

> and do i need to change version number for publishing?

Nope, we use `semantic-release` library to automatically manage versioning.

**Comment by ElvisYang** [comment]
Thanks @dziraf

**Pull request merged**
